//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission
{
    using System;
    using System.Collections.Generic;
    
    public partial class days
    {
        public decimal id { get; set; }
        public Nullable<System.DateTime> dateT { get; set; }
        public string attendents { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isPrimer { get; set; }
        public int count { get; set; }
    }
}
