//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class missionTimeEntities : DbContext
    {
        public missionTimeEntities()
            : base("name=missionTimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dayOffs> dayOffs { get; set; }
        public virtual DbSet<days> days { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<missions> missions { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<demandDays> demandDays { get; set; }
        public virtual DbSet<missionListView> missionListView { get; set; }
    }
}
