//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission
{
    using System;
    using System.Collections.Generic;
    
    public partial class missionListView
    {
        public Nullable<decimal> attendantID { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> dateT { get; set; }
        public decimal id { get; set; }
    }
}
