//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public Nullable<decimal> departmantId { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<bool> statu { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public departments deptsName { get; set; }
    }
}
